[versions]
# plugins version
kotlin = "1.9.23"
dokka = "1.9.10"
korro = "0.1.6"
nexus = "1.3.0"
jupyterApi = "0.12.0-219"

# libraries version
dataframe = "0.13.1"
serialization = "1.6.3"
datetime = "0.6.0"
html = "0.11.0"
statistics = "0.3.0-dev-23"
letsPlot = "4.7.3"
letsPlotImage = "4.3.3"
mockk = "1.13.10"

[libraries]
# Kotlinx libraries
kotlinx-dataframe = { group = "org.jetbrains.kotlinx", name = "dataframe", version.ref = "dataframe" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-html = { group = "org.jetbrains.kotlinx", name = "kotlinx-html-jvm", version.ref = "html" }
kotlinx-statistics = { group = "org.jetbrains.kotlinx", name = "kotlin-statistics-jvm", version.ref = "statistics" }
# Lets-Plot
lets-plot = { group = "org.jetbrains.lets-plot", name = "lets-plot-kotlin-jvm", version.ref = "letsPlot" }
lets-plot-image = { group = "org.jetbrains.lets-plot", name = "lets-plot-image-export", version.ref = "letsPlotImage" }
lets-plot-awt = { group = "org.jetbrains.lets-plot", name = "platf-awt-jvm", version.ref = "letsPlotImage" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }



[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jupyter-api = { id = "org.jetbrains.kotlin.jupyter.api", version.ref = "jupyterApi" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
korro = { id = "io.github.devcrocod.korro", version.ref = "korro" }

