[versions]
# plugins version
kotlin = "1.9.23"
dokka = "1.9.10"
korro = "0.1.6"
nexus = "1.3.0"
jupyterApi = "0.12.0-250"

# libraries version
dataframe = "0.15.0"
serialization = "1.6.3"
datetime = "0.6.0"
html = "0.11.0"
statistics = "0.4.0-dev-8"
letsPlot = "4.9.2"
letsPlotImage = "4.5.1"
mockk = "1.13.10"
geotools = "32.1"
jai-core = "1.1.3"

[libraries]
# Kotlinx libraries
kotlinx-dataframe = { group = "org.jetbrains.kotlinx", name = "dataframe", version.ref = "dataframe" }
kotlinx-dataframe-geo = { group = "org.jetbrains.kotlinx", name = "dataframe-geo", version.ref = "dataframe" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-html = { group = "org.jetbrains.kotlinx", name = "kotlinx-html-jvm", version.ref = "html" }
kotlinx-statistics = { group = "org.jetbrains.kotlinx", name = "kotlin-statistics-jvm", version.ref = "statistics" }
# Lets-Plot
lets-plot = { group = "org.jetbrains.lets-plot", name = "lets-plot-kotlin-jvm", version.ref = "letsPlot" }
lets-plot-image = { group = "org.jetbrains.lets-plot", name = "lets-plot-image-export", version.ref = "letsPlotImage" }
lets-plot-awt = { group = "org.jetbrains.lets-plot", name = "platf-awt-jvm", version.ref = "letsPlotImage" }
lets-plot-geotools = { group = "org.jetbrains.lets-plot", name = "lets-plot-kotlin-geotools", version.ref = "letsPlot" }
#Geootools
jai-core = { module = "javax.media:jai-core", version.ref = "jai-core" }

geotools-main = { module = "org.geotools:gt-main", version.ref = "geotools" }
geotools-shapefile = { module = "org.geotools:gt-shapefile", version.ref = "geotools" }
geotools-geojson = { module = "org.geotools:gt-geojson", version.ref = "geotools" }
geotools-referencing = { module = "org.geotools:gt-referencing", version.ref = "geotools" }
geotools-epsg-hsql = { module = "org.geotools:gt-epsg-hsql", version.ref = "geotools" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }



[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jupyter-api = { id = "org.jetbrains.kotlin.jupyter.api", version.ref = "jupyterApi" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
korro = { id = "io.github.devcrocod.korro", version.ref = "korro" }

